openapi: 3.0.0
info:
  title: Quiz REST API
  version: '1.0'
  description: This is a REST API for a quiz application.
servers:
  - url: http://localhost:8080
paths:
  /quiz/api/v1/questions:
    get:
      summary: Get list of questions
      description: Get a list of all questions.
      responses:
        '200':
          description: A list of questions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
  /quiz/api/v1/answers:
    post:
      summary: Submit answers
      description: Submit answers to the quiz.
      parameters:
        - name: user
          in: query
          required: true
          description: The user ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswerMatrix'
      responses:
        '201':
          description: Answers submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerMatrix'
  /quiz/api/v1/user/{user}/statistics:
    get:
      summary: Get user statistics
      description: Get statistics for a specific user.
      parameters:
        - name: user
          in: path
          required: true
          description: The user ID
          schema:
            type: string
      responses:
        '200':
          description: User statistics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistic'
components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: integer
          format: int32
        query:
          type: string
        answers:
          type: array
          items:
            type: string
        correctAnswer:
          type: integer
          format: int32
    Answer:
      type: object
      properties:
        questionId:
          type: integer
          format: int32
        answerId:
          type: integer
          format: int32
    AnswerMatrix:
      type: object
      properties:
        score:
          type: integer
          format: int32
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
    Statistic:
      type: object
      properties:
        userScore:
          type: integer
          format: int32
        worseQuizzersRatio:
          type: number
          format: float
        totalQuizzers:
          type: integer
          format: int32
